db:
 url: "jdbc:postgresql://aws-0-ap-south-1.pooler.supabase.com:5432/postgres"
 driverClass: "org.postgresql.Driver"
 username: "postgres.tzddaaidpmoucoypdwry"
 password: "![JPqUS8TbYsLvgmSU5+sxYAQw+BLlpAFz]"
 