name: Publish to Exchange & Deploy to CloudHub 2.0 (Dev & UAT)

on:
  push:
    branches: 
      - dev
      - uat
      - main


jobs:
  Publish_to_Exchange:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
 
      - name: Increment Version
        run: |
          CURRENT_VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
          NEW_VERSION=$(echo $CURRENT_VERSION | awk -F. -v OFS=. '{$NF += 1 ; print}')
          echo "New version: $NEW_VERSION"
          mvn versions:set -DnewVersion=$NEW_VERSION -DgenerateBackupPoms=false
 
      - name: Commit and Push Changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          BRANCH_NAME=$(echo ${GITHUB_REF#refs/heads/})
          echo "Pushing changes to branch: $BRANCH_NAME"
          git checkout $BRANCH_NAME
          git pull origin $BRANCH_NAME
          git commit -am "chore: Increment POM version to $NEW_VERSION [skip ci]"
          git push origin $BRANCH_NAME
          
      - name: Check Default Maven Version
        run: mvn -version
 
      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven-
 
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: "zulu"
          java-version: 17
          
      - name: Publish to Exchange
        shell: bash
        run: |
          echo "Publishing to Exchange"
          mvn clean deploy --settings .maven/settings.xml -DskipMunitTests  \
            -Dclient.id="${{ secrets.DEV_CLIENT_ID }}" \
            -Dclient.secret="${{ secrets.DEV_CLIENT_SECRET }}"


  deploy-to-cloudhub-dev:
    needs: Publish_to_Exchange
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Pull the latest changes from dev branch
        run: |
          git fetch origin
          git checkout dev
          git pull origin dev

      - name: Echo version from pom.xml
        run: |
          VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
          echo "Using version $VERSION"    
          
      - name: Build and Deploy to DEV
        shell: bash
        run: |
          mvn clean deploy --settings .maven/settings.xml -DskipMunitTests -DmuleDeploy \
            -Dclient.id="${{ secrets.DEV_CLIENT_ID }}" \
            -Dclient.secret="${{ secrets.DEV_CLIENT_SECRET }}" \
            -DcloudhubEnvironment="dev" \
            -Dtarget="Cloudhub-US-East-2" \
            -Denv="dev" \

  deploy-to-cloudhub-uat:
    needs: Publish_to_Exchange
    runs-on: ubuntu-latest
    environment: uat
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Pull the latest changes from dev branch
        run: |
          git fetch origin
          git checkout uat
          git pull origin uat

      - name: Echo version from pom.xml
        run: |
          VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
          echo "Using version $VERSION"    
          
      - name: Build and Deploy to UAT
        shell: bash
        run: |
          mvn clean deploy --settings .maven/settings.xml -DskipMunitTests -DmuleDeploy \
            -Dclient.id="${{ secrets.UAT_CLIENT_ID }}" \
            -Dclient.secret="${{ secrets.UAT_CLIENT_SECRET }}" \
            -DcloudhubEnvironment="uat" \
            -Dtarget="Cloudhub-US-East-2" \
            -Denv="uat" \
